const KEY='cm_admin_data_v1';
const defaults={users:[{id:1,name:'محمود',email:'admin@codemaster.local',role:'Admin',xp:999,last:'اليوم',status:'نشط'},{id:2,name:'أحمد علي',email:'ahmed@example.com',role:'Student',xp:420,last:'اليوم',status:'نشط'},{id:3,name:'سارة محمد',email:'sara@example.com',role:'Student',xp:760,last:'أمس',status:'نشط'},{id:4,name:'يوسف',email:'yousef@example.com',role:'Student',xp:180,last:'قبل 3 أيام',status:'نشط'}],courses:[{id:1,title:'HTML من الصفر',tech:'HTML',level:'مبتدئ',lessons:8,students:142},{id:2,title:'CSS Pro',tech:'CSS',level:'مبتدئ',lessons:10,students:98},{id:3,title:'JavaScript Mastery',tech:'JavaScript',level:'متوسط',lessons:18,students:231},{id:4,title:'Python للمبتدئين',tech:'Python',level:'مبتدئ',lessons:12,students:177},{id:5,title:'C++ Fundamentals',tech:'C++',level:'متوسط',lessons:14,students:86},{id:6,title:'SQL عملي',tech:'SQL',level:'متوسط',lessons:9,students:113}],lessons:[{id:1,title:'ما هي HTML؟',course:'HTML من الصفر',video:'',date:'اليوم'},{id:2,title:'Selectors في CSS',course:'CSS Pro',video:'',date:'أمس'},{id:3,title:'المتغيرات في JavaScript',course:'JavaScript Mastery',video:'',date:'قبل يومين'}],activity:[{text:'تم فتح لوحة الإدارة',date:'الآن'},{text:'تم نشر دورة JavaScript Mastery',date:'اليوم'},{text:'تم تسجيل مستخدم جديد',date:'اليوم'},{text:'تم إكمال درس HTML',date:'أمس'}],settings:{siteName:'CodeMaster',siteDesc:'منصة عربية مجانية لتعلم البرمجة.',maintenance:false}};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||defaults; const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(KEY,JSON.stringify(data))} function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
const titles={overview:'نظرة عامة',users:'المستخدمون',courses:'الدورات',content:'المحتوى',activity:'النشاط',settings:'الإعدادات'};
function render(){
 $('#statUsers').textContent=data.users.length; $('#statCourses').textContent=data.courses.length; $('#statLessons').textContent=data.lessons.length; $('#statProgress').textContent=(Math.min(99,Math.round((data.lessons.length*7+data.users.length*2))))+'%';
 $('#recentUsers').innerHTML=data.users.slice(-5).reverse().map(u=>`<tr><td><b>${esc(u.name)}</b></td><td>${esc(u.email)}</td><td>${esc(u.last)}</td><td><span class="status">● ${esc(u.status)}</span></td></tr>`).join('');
 $('#usersTable').innerHTML=data.users.map(u=>`<tr><td><b>${esc(u.name)}</b></td><td>${esc(u.email)}</td><td>${esc(u.role)}</td><td>${u.xp}</td><td>${esc(u.last)}</td><td><button class="ghost" onclick="editUser(${u.id})">تعديل</button> <button class="ghost danger" onclick="removeUser(${u.id})">حذف</button></td></tr>`).join('');
 $('#coursesGrid').innerHTML=data.courses.map(c=>`<article class="course-card"><span class="tag">${esc(c.tech)} • ${esc(c.level)}</span><h3>${esc(c.title)}</h3><p>${c.lessons} دروس • ${c.students} طالب</p><div class="course-actions"><button onclick="editCourse(${c.id})">تعديل</button><button class="danger" onclick="removeCourse(${c.id})">حذف</button></div></article>`).join('');
 $('#lessonCourse').innerHTML=data.courses.map(c=>`<option>${esc(c.title)}</option>`).join('');
 $('#lessonsList').innerHTML=data.lessons.slice().reverse().map(l=>`<div class="lesson"><b>${esc(l.title)}</b><small>${esc(l.course)} • ${esc(l.date)}</small></div>`).join('');
 $('#activityList').innerHTML=data.activity.slice().reverse().map(a=>`<div class="activity"><b>${esc(a.text)}</b><small>${esc(a.date)}</small></div>`).join('');
 const chart=[32,51,38,67,58,84,72]; $('#activityChart').innerHTML=chart.map((v,i)=>`<div class="bar" style="height:${v}%"><small>${['س','ح','ن','ث','ر','خ','ج'][i]}</small></div>`).join('');
}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function log(text){data.activity.push({text,date:'الآن'});save();render()}
function show(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v).classList.add('active');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#viewTitle').textContent=titles[v];window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='newCourse')openCourse();if(a==='newUser')openUser();if(a==='content')show('content');if(a==='backup')exportData()});
function openUser(user={}){const editing=!!user.id;$('#modalCard').innerHTML=`<span class="eyebrow">${editing?'EDIT USER':'NEW USER'}</span><h2>${editing?'تعديل المستخدم':'إضافة مستخدم'}</h2><label>الاسم<input id="mName" value="${esc(user.name||'')}"></label><label>البريد<input id="mEmail" value="${esc(user.email||'')}"></label><label>الدور<select id="mRole"><option ${user.role==='Student'?'selected':''}>Student</option><option ${user.role==='Admin'?'selected':''}>Admin</option></select></label><div class="actions"><button class="ghost" onclick="closeModal()">إلغاء</button><button class="primary" onclick="saveUser(${user.id||0})">حفظ</button></div>`;$('#modal').classList.add('open')}
function saveUser(id){const name=$('#mName').value.trim(),email=$('#mEmail').value.trim(),role=$('#mRole').value;if(!name||!email)return toast('أكمل البيانات');if(id){Object.assign(data.users.find(x=>x.id===id),{name,email,role});log('تم تعديل مستخدم')}else{data.users.push({id:Date.now(),name,email,role,xp:0,last:'الآن',status:'نشط'});log('تمت إضافة مستخدم جديد')}save();closeModal();render();toast('تم الحفظ بنجاح')}
function editUser(id){openUser(data.users.find(x=>x.id===id))} function removeUser(id){if(!confirm('حذف المستخدم؟'))return;data.users=data.users.filter(x=>x.id!==id);log('تم حذف مستخدم');save();render();toast('تم الحذف')}
function openCourse(course={}){const editing=!!course.id;$('#modalCard').innerHTML=`<span class="eyebrow">${editing?'EDIT COURSE':'NEW COURSE'}</span><h2>${editing?'تعديل دورة':'إضافة دورة'}</h2><label>اسم الدورة<input id="mTitle" value="${esc(course.title||'')}"></label><label>التقنية<input id="mTech" value="${esc(course.tech||'')}"></label><label>المستوى<select id="mLevel"><option>مبتدئ</option><option ${course.level==='متوسط'?'selected':''}>متوسط</option><option ${course.level==='متقدم'?'selected':''}>متقدم</option></select></label><div class="actions"><button class="ghost" onclick="closeModal()">إلغاء</button><button class="primary" onclick="saveCourse(${course.id||0})">حفظ</button></div>`;$('#modal').classList.add('open')}
function saveCourse(id){const title=$('#mTitle').value.trim(),tech=$('#mTech').value.trim(),level=$('#mLevel').value;if(!title||!tech)return toast('أكمل البيانات');if(id)Object.assign(data.courses.find(x=>x.id===id),{title,tech,level});else data.courses.push({id:Date.now(),title,tech,level,lessons:0,students:0});log(id?'تم تعديل دورة':'تمت إضافة دورة جديدة');save();closeModal();render();toast('تم الحفظ')}
function editCourse(id){openCourse(data.courses.find(x=>x.id===id))} function removeCourse(id){if(!confirm('حذف الدورة؟'))return;data.courses=data.courses.filter(x=>x.id!==id);log('تم حذف دورة');save();render();toast('تم الحذف')}
function closeModal(){$('#modal').classList.remove('open')} window.closeModal=closeModal;window.editUser=editUser;window.removeUser=removeUser;window.editCourse=editCourse;window.removeCourse=removeCourse;window.saveUser=saveUser;window.saveCourse=saveCourse;
$('#addLesson').onclick=()=>{const title=$('#lessonTitle').value.trim(),course=$('#lessonCourse').value,video=$('#lessonVideo').value.trim(),desc=$('#lessonDesc').value.trim();if(!title)return toast('اكتب عنوان الدرس');data.lessons.push({id:Date.now(),title,course,video,desc,date:'الآن'});const c=data.courses.find(x=>x.title===course);if(c)c.lessons++;log('تمت إضافة درس جديد');save();render();$('#lessonTitle').value='';$('#lessonVideo').value='';$('#lessonDesc').value='';toast('تم نشر الدرس')}
$('#userSearch').oninput=e=>{const q=e.target.value.toLowerCase();$$('#usersTable tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')};
$('#saveSettings').onclick=()=>{data.settings.siteName=$('#siteName').value;data.settings.siteDesc=$('#siteDesc').value;data.settings.maintenance=$('#maintenance').checked;log('تم حفظ إعدادات المنصة');toast('تم حفظ الإعدادات')};
$('#clearActivity').onclick=()=>{data.activity=[];save();render();toast('تم مسح السجل')};
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='codemaster-backup.json';a.click();URL.revokeObjectURL(a.href);toast('تم تصدير النسخة الاحتياطية')};$('#exportBtn').onclick=exportData;
$('#theme').onclick=()=>{document.body.classList.toggle('light');$('#theme').textContent=document.body.classList.contains('light')?'☀':'☾'};
$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$('#siteName').value=data.settings.siteName;$('#siteDesc').value=data.settings.siteDesc;$('#maintenance').checked=data.settings.maintenance;render();
